### ISSUE TITLE
CLI: Gives error on Linux

### ISSUE THREAD

**Issue by sahildua2305** [gillstrom/battery-level#7]
```
Error: Command failed: upower -e

(upower:13207): libupower-glib-WARNING **: Couldn't enumerate devices: Message did not receive a reply (timeout by message bus)

(upower:13207): UPower-WARNING **: failed to enumerate: Message did not receive a reply (timeout by message bus)

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

Tested on `Linux 3.16.0-71-generic x86_64`

**Comment by kevva** [comment]
This is not a bug caused by this module but rather something in your system. https://www.google.com/search?q=Couldn%27t+enumerate+devices%3A+Message+did+not+receive+a+reply+(timeout+by+message+bus)&oq=Couldn%27t+enumerate+devices%3A+Message+did+not+receive+a+reply+(timeout+by+message+bus)&aqs=chrome..69i57.1244j0j7&sourceid=chrome&ie=UTF-8.
